/*
<metadata>
<name>dd</name>
<description><p>dd</p></description>
<url>dd</url>
<status>Completed</status>
<remarks>dd</remarks>
<date>2026-08-02</date>
<level>Easy</level>
<notes><p>dd</p></notes>
<companies>dd</companies>
<concepts>dd</concepts>
</metadata>
*/
kk