/*
<metadata>
<name>Erase First or Second Letter</name>
<description>You are given a string s of length n.

Let's define two operations you can apply on the string: 
- remove the first character of the string;  
- remove the second character of the string. 

Your task is to find the number of distinct non-empty strings that can be generated by applying the given operations on the initial string any number of times (possibly zero), in any order.</description>
<url>https://codeforces.com/problemset/problem/1917/B</url>
<status>Completed</status>
<date>2026-06-23</date>
<level>Easy</level>
</metadata>
*/
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int t = sc.nextInt();

        while (t-- > 0) {
            int n = sc.nextInt();
            String s = sc.next();

            boolean[] seen = new boolean[26];
            long ans = 0;

            for (int i = 0; i < n; i++) {
                int idx = s.charAt(i) - 'a';

                if (!seen[idx]) {
                    ans += (n - i);
                    seen[idx] = true;
                }
            }

            System.out.println(ans);
        }
    }
}