/*
<metadata>
<name>Erase First or Second Letter</name>
<description>You are given a string s of length n.

Let's define two operations you can apply on the string: 
- remove the first character of the string;  
- remove the second character of the string. 

Your task is to find the number of distinct non-empty strings that can be generated by applying the given operations on the initial string any number of times (possibly zero), in any order.

Input

5
5
aaaaa
1
z
5
ababa
14
bcdaaaabcdaaaa
20
abcdefghijklmnopqrst

Output

5
1
9
50
210

</description>
<url>https://codeforces.com/problemset/problem/1917/B</url>
<status>Completed</status>
<date>2026-06-23</date>
<level>Easy</level>
<notes>The trick is to understand what strings can actually be formed. 

Observation 1
You have two operations:

Remove the first character.

Remove the second character.

Suppose
s = abcde
You can always delete characters before some position i, so every generated string starts from some suffix s[i...].
Inside that suffix, you may remove the second character repeatedly, allowing you to keep or delete later characters. 

Observation 2 (Key)
For every starting position i, the number of new strings contributed is:

1 if s[i] has already appeared before.

i + 1? No.

The actual result is much simpler:
When scanning left to right:

If the current character is seen for the first time, it contributes (n - i) new strings.

Otherwise, it contributes 0. 

Why?
If this is the first occurrence of a character, then every suffix starting here is unique because no earlier suffix can start with this character.
Example:
ababa
i = 0, 'a' first timecontribution = 5i = 1, 'b' first timecontribution = 4i = 2, 'a' seen+0i = 3, 'b' seen+0i = 4, 'a' seen+0Answer = 5 + 4 = 9
Matches the sample.</notes>
</metadata>
*/
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int t = sc.nextInt();

        while (t-- > 0) {
            int n = sc.nextInt();
            String s = sc.next();

            boolean[] seen = new boolean[26];
            long ans = 0;

            for (int i = 0; i < n; i++) {
                int idx = s.charAt(i) - 'a';

                if (!seen[idx]) {
                    ans += (n - i);
                    seen[idx] = true;
                }
            }

            System.out.println(ans);
        }
    }
}